package modelo.entidad;
// Generated 05-08-2022 02:05:17 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * FormaPago generated by hbm2java
 */
public class FormaPago  implements java.io.Serializable {


     private int idFormaPago;
     private String nombreFormaPago;
     private Set<Remesa> remesas = new HashSet<Remesa>(0);

    public FormaPago() {
    }

	
    public FormaPago(int idFormaPago) {
        this.idFormaPago = idFormaPago;
    }
    public FormaPago(int idFormaPago, String nombreFormaPago, Set<Remesa> remesas) {
       this.idFormaPago = idFormaPago;
       this.nombreFormaPago = nombreFormaPago;
       this.remesas = remesas;
    }
   
    public int getIdFormaPago() {
        return this.idFormaPago;
    }
    
    public void setIdFormaPago(int idFormaPago) {
        this.idFormaPago = idFormaPago;
    }
    public String getNombreFormaPago() {
        return this.nombreFormaPago;
    }
    
    public void setNombreFormaPago(String nombreFormaPago) {
        this.nombreFormaPago = nombreFormaPago;
    }
    public Set<Remesa> getRemesas() {
        return this.remesas;
    }
    
    public void setRemesas(Set<Remesa> remesas) {
        this.remesas = remesas;
    }




}


