package modelo.entidad;
// Generated 05-08-2022 02:05:17 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Remesa generated by hbm2java
 */
public class Remesa  implements java.io.Serializable {


     private Integer idRemesa;
     private Cliente cliente;
     private Estado estado;
     private FormaPago formaPago;
     private Pais pais;
     private Usuario usuario;
     private String nombreBeneficiario;
     private Double monto;
     private Double comision;
     private String clave;
     private Date fechaEnvio;
     private Date fechaRecepcion;
     private Date fechaExpira;

    public Remesa() {
    }

    public Remesa(Cliente cliente, Estado estado, FormaPago formaPago, Pais pais, Usuario usuario, String nombreBeneficiario, Double monto, Double comision, String clave, Date fechaEnvio, Date fechaRecepcion, Date fechaExpira) {
       this.cliente = cliente;
       this.estado = estado;
       this.formaPago = formaPago;
       this.pais = pais;
       this.usuario = usuario;
       this.nombreBeneficiario = nombreBeneficiario;
       this.monto = monto;
       this.comision = comision;
       this.clave = clave;
       this.fechaEnvio = fechaEnvio;
       this.fechaRecepcion = fechaRecepcion;
       this.fechaExpira = fechaExpira;
    }
   
    public Integer getIdRemesa() {
        return this.idRemesa;
    }
    
    public void setIdRemesa(Integer idRemesa) {
        this.idRemesa = idRemesa;
    }
    public Cliente getCliente() {
        return this.cliente;
    }
    
    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }
    public Estado getEstado() {
        return this.estado;
    }
    
    public void setEstado(Estado estado) {
        this.estado = estado;
    }
    public FormaPago getFormaPago() {
        return this.formaPago;
    }
    
    public void setFormaPago(FormaPago formaPago) {
        this.formaPago = formaPago;
    }
    public Pais getPais() {
        return this.pais;
    }
    
    public void setPais(Pais pais) {
        this.pais = pais;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public String getNombreBeneficiario() {
        return this.nombreBeneficiario;
    }
    
    public void setNombreBeneficiario(String nombreBeneficiario) {
        this.nombreBeneficiario = nombreBeneficiario;
    }
    public Double getMonto() {
        return this.monto;
    }
    
    public void setMonto(Double monto) {
        this.monto = monto;
    }
    public Double getComision() {
        return this.comision;
    }
    
    public void setComision(Double comision) {
        this.comision = comision;
    }
    public String getClave() {
        return this.clave;
    }
    
    public void setClave(String clave) {
        this.clave = clave;
    }
    public Date getFechaEnvio() {
        return this.fechaEnvio;
    }
    
    public void setFechaEnvio(Date fechaEnvio) {
        this.fechaEnvio = fechaEnvio;
    }
    public Date getFechaRecepcion() {
        return this.fechaRecepcion;
    }
    
    public void setFechaRecepcion(Date fechaRecepcion) {
        this.fechaRecepcion = fechaRecepcion;
    }
    public Date getFechaExpira() {
        return this.fechaExpira;
    }
    
    public void setFechaExpira(Date fechaExpira) {
        this.fechaExpira = fechaExpira;
    }




}


