package modelo.entidad;
// Generated 05-08-2022 02:05:17 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * TipoDocumento generated by hbm2java
 */
public class TipoDocumento  implements java.io.Serializable {


     private Integer idTipoDocumento;
     private String nombreTipoDocumento;
     private Set<Cliente> clientes = new HashSet<Cliente>(0);

    public TipoDocumento() {
    }

    public TipoDocumento(String nombreTipoDocumento, Set<Cliente> clientes) {
       this.nombreTipoDocumento = nombreTipoDocumento;
       this.clientes = clientes;
    }
   
    public Integer getIdTipoDocumento() {
        return this.idTipoDocumento;
    }
    
    public void setIdTipoDocumento(Integer idTipoDocumento) {
        this.idTipoDocumento = idTipoDocumento;
    }
    public String getNombreTipoDocumento() {
        return this.nombreTipoDocumento;
    }
    
    public void setNombreTipoDocumento(String nombreTipoDocumento) {
        this.nombreTipoDocumento = nombreTipoDocumento;
    }
    public Set<Cliente> getClientes() {
        return this.clientes;
    }
    
    public void setClientes(Set<Cliente> clientes) {
        this.clientes = clientes;
    }




}


